theme = "base16_transparent"

[editor]
scrolloff                   = 0
mouse                       = true
middle-click-paste          = true
scroll-lines                = 3
# shell                       = "zsh"
line-number                 = "relative"
cursorline                  = false
gutters                     = ["diagnostics", "line-numbers"]
auto-completion             = true
auto-format                 = true
idle-timeout                = 400
completion-trigger-len      = 1
auto-info                   = true
true-color                  = true
rulers                      = []
color-modes                 = false

# [editor.statusline]

[editor.lsp]
display-messages            = false
auto-signature-help         = true
display-signature-help-docs = false

[editor.cursor-shape]
normal                      = "block"
insert                      = "block"
select                      = "block"

[editor.file-picker]
hidden                      = false
parents                     = true
ignore                      = true
git-ignore                  = true
git-global                  = true
git-exclude                 = true
# max-depth                   = "None"

# [editor.auto-pairs]

[editor.search]
smart-case                  = true
wrap-around                 = true

[editor.whitespace]
# render                      = "all"
# characters                  = 

[editor.indent-guides]
render                      = false
character                   = " "

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
